spring.application.name=Accounts
spring.data.mongodb.uri=mongodb://vigneshuvari_db_user:94zI8NnFviJhp1Dk@ac-q2rdkok-shard-00-00.wcjxsbk.mongodb.net:27017,ac-q2rdkok-shard-00-01.wcjxsbk.mongodb.net:27017,ac-q2rdkok-shard-00-02.wcjxsbk.mongodb.net:27017/?ssl=true&replicaSet=atlas-zzatu1-shard-0&authSource=admin&appName=Cluster0
spring.data.mongodb.database=employee_db
server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=vigneshuvari@gmail.com
spring.mail.password=hxtk tybg fite cpnn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true