spring:
  application:
    name: Accounts

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: employee_db

server:
  port: ${PORT}
  address: 0.0.0.0

file:
  upload-dir: uploads/

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}