#spring:
#  data:
#    mongodb:
#      uri: ${mongodb+srv://vigneshuvari_db_user:94zI8NnFviJhp1Dk@cluster0.wcjxsbk.mongodb.net/?appName=Cluster0}

      spring:
        application:
          name: Accounts

        data:
          mongodb:
            uri: ${MONGODB_URI}
            database: employee_db

        mail:
          host: smtp.gmail.com
          port: 587
          username: ${MAIL_USERNAME}
          password: ${MAIL_PASSWORD}
          properties:
            mail:
              smtp:
                auth: true
                starttls:
                  enable: true

      server:
        port: ${PORT:8080}